regist/config/routes.rb
Rails.application.routes.draw do

  root 'friends#top'

  get '/top'=>'friends#top'
  get '/account'=>'friends#account'
  post '/mypage'=>'friends#mypage'
  get '/invite'=>'friends#invite'
  post '/end'=>'friends#end'

end

regist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

regist/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def top
  end
  def account
  end
  def mypage
  end
  def invite
  end
  def end
  end
end

regist/app/helpers/application_helper.rb
module ApplicationHelper
end

regist/app/helpers/friends_helper.rb
module FriendsHelper
end

regist/app/views/friends/account.html.erb
<body>
  <h4></h4>
  <div>
    <p>create your account</p>
    <hr>
    <%=form_tag mypage_path do%>
    <p><input type="text" placeholder="name"></p>
    <p><input type="email" placeholder="email"></p>
    <p><input type="password" placeholder="password"></p>
    <p><input type="submit" value="CREATE"></p>
    <%end%>
  </div>
</body>

regist/app/views/friends/end.html.erb
<body>
  <div>
    <p>DONE</p>
    <hr>
    <%=link_to "back to toppage",top_path%>
  </div>
</body>

regist/app/views/friends/invite.html.erb
<body>
  <div>
    <p>send an invitation</p>
    <hr>
    <%=form_tag end_path do%>
    <p><input type="email" placeholder="email"></p>
    <p><input type="submit" value="SEND"></p>
    <%end%>
  </div>
</body>

regist/app/views/friends/mypage.html.erb
<body>
  <div>
    <p>login succeeded</p>
    <hr>
    <%=link_to "INVITE FRIENDS",invite_path%>
  </div>
</body>

regist/app/views/friends/top.html.erb
<body>
  <h4></h4>
  <div>
    <p>this is a service to invite your friends</p>
    <hr>
    <%=link_to "START",account_path%>
  </div>
</body>

regist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Regist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>